apiVersion : apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: rymcloneregistry.azurecr.io/authservice
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: s6rymclonegeheimpje