apiVersion: v1
kind: Service
metadata:
    name: userservice
spec:
    type: LoadBalancer
    ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
    selector:
        app: userservice