apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: s6rymcloneregistry.azurecr.io/databases/postgres
          imagePullPolicy: "IfNotPresent"
          env:
            - name: "POSTGRES_USER"
              value: "s6rymclone"
            - name: "POSTGRES_PASSWORD"
              value: "ditisgeensecret"
            - name: "POSTGRES_DB"
              value: "s6rymclone"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      imagePullSecrets:
        - name: s6rymclonegeheimpje

      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim