name: Build ApiGateway

on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - "ApiGateway/**"
      - ".github/workflows/api-gateway-build.yml"
  pull_request:
    branches: 
      - main
      - dev
    paths:
      - "ApiGateway/**"
      - ".github/workflows/api-gateway-build.yml"

env:
  PROJECT_PATH: 'ApiGateway/ApiGateway/ApiGateway.csproj'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: Setup docker
      uses: docker/setup-buildx-action@v1

    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
       context: .
       file: ApiGateway/Dockerfile
       push: true
       tags: ${{ secrets.DOCKERHUB_USERNAME }}/rymclone-gateway:latest
