name: Build ApiGateway

on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - "ApiGateway/**"
      - ".github/workflows/api-gateway-build.yml"
  pull_request:
    branches: 
      - main
      - dev
    paths:
      - "ApiGateway/**"
      - ".github/workflows/api-gateway-build.yml"

env:
  PROJECT_PATH: 'ApiGateway/ApiGateway/ApiGateway.csproj'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_NAME: 's6rymcloneregistry'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: 'Test project'
      run: dotnet test

    
    - name: 'Azure container login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container Registry (ACR)
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
      working-directory: ./<path-to-Dockerfile-directory>
